version: "3.0"

services:
  typo-image-gen:
    container_name: typo-image-gen
    build:
      context: ../
      dockerfile: .docker/Dockerfile 
    restart: unless-stopped
    environment:
      - GRPC_VALMAR_URL=http://localhost:5175
