version: "3.0"

services:
  typo-content-service:
    container_name: typo-content-gen
    build:
      context: ../
      dockerfile: .docker/Dockerfile 
    restart: unless-stopped
    environment:
      - GRPC_VALMAR_URL=http://host.docker.internal:5175
    ports:
      - "5221:8080"