name: Build and Publish

on:
  push:
    branches:
      - main
        
jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
          
      - name: Generate Version Date
        id: version-date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
        
      - name: Build
        run: dotnet build Client/Client.csproj --configuration Release
        
      - name: Package
        run: >
          dotnet pack Client/Client.csproj --no-restore --no-build --configuration Release
          -p:PackageVersion=${{ steps.version-date.outputs.date }}-$(echo $GITHUB_SHA | cut -c1-7)
          
      - name: Publish
        run: >
          dotnet nuget push Client.${{ steps.version-date.outputs.date }}-$(echo $GITHUB_SHA | cut -c1-7).nupkg 
          -s https://nuget.pkg.github.com/toobeeh/index.json
          -k ${{ secrets.NUGET_AUTH_TOKEN }}
        
        